graphhopper:
  graph.flag_encoders: car,foot
  graph.encoded_values: road_class,road_class_link,road_environment,max_speed,road_access,surface,toll,track_type
  datareader.preferred_language: en
  graph.do_sort: true
  prepare.min_network_size: 1
  prepare.min_one_way_network_size: 1
  routing.non_ch.max_waypoint_distance: 1000000
  graph.dataaccess: RAM_STORE
  profiles:
    - name: car
      vehicle: car
      weighting: fastest
    - name: foot
      vehicle: foot
      weighting: fastest
  profiles_ch:
    - profile: car
    - profile: foot
server:
  application_connectors:
  - type: http
    port: 8989
    bind_host: localhost
  request_log:
      appenders: []
  admin_connectors:
  - type: http
    port: 8990
    bind_host: localhost
